spring:
  security:
    user:
      password: 1234
    oauth2:
      client:
        registration:
          userInfoUri: http://localhost:9999/uaa/user
server:
  address: 127.0.0.1
  port: 9000
logging:
  level:
    org.springframework:
      security: DEBUG
      session: TRACE  