spring:
  security:
    user:
      password: 1234
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/userinfo
server:
  address: 127.0.0.1
  port: 9000
logging:
  level:
    org.springframework:
      security: DEBUG
      session: TRACE